version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-app
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
    env_file:
      - .env
    networks:
      - todo-network
  nginx:
    image: nginx:stable-alpine
    container_name: todo-nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - todo-network
  db:
    image: mysql:8.0
    container_name: todo-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  db-data:
    driver: local